version: 2

sources :
  - name : gz_raw_data
    description : Location du dossier contenant la raw data
    tables:
      - name: raw_gz_product
      - name : raw_gz_sales
      - name : raw_gz_ship